### PR TITLE
Fixed 'small Text' font family [inter to sans-serif]

### PR DESCRIPTION
**Pull request by madara-uchihaaa**

### CODE REVIEW

**Comment by MLGPenguin** [comment]
closes #191

**Comment by stephendotgg** [comment]
This does not fix the font in the text area, right? We would need both of these to have the tag. See: 

image

**Comment by joshbker** [comment]
Hey! Thanks for your PR, however I believe this would not resolve the problem, have you actually tested this? 

We override Tailwind's `sans` font, as all text globally by default is `font-sans`: [tailwind.config.cjs](https://github.com/flytegg/mc-utils/blob/master/tailwind.config.cjs#L7)

**Comment by madara-uchihaaa** [comment]
Ohky , you are ohky , I may work and update the pr as requested.

**Comment by stephendotgg** [comment]
> Ohky , If you are agree , I may work and update the pr as requested.

thank you!

**Comment by madara-uchihaaa** [comment]
> > Ohky , If you are agree , I may work and update the pr as requested.
> 
> thank you!

Should I proceed to fix , or not ?

**Comment by Pan-nav** [comment]
> > > Ohky , If you are agree , I may work and update the pr as requested.
> > 
> > 
> > thank you!
> 
> Should I proceed to fix , or not ?

Yes, go ahead

**Comment by stephendotgg** [comment]
Closing, I fixed this.

**Pull request closed without merging**
