### PR TITLE
[New Util]: Custom Heads Database

### PR DESCRIPTION
**Pull request by StillLutto**
This Pull Request was made to add a new util, #183. The utility in question is basically a place for people to find for custom heads they can then use in their worlds.

It looks something like this:
image

## Features
- You can switch categories
- Only 20 heads are loaded initially, then you can load more by clicking on the button below the heads
- You can search for heads
- You can copy the head `/give` commands

## Code Changes/Additions
- Fetch all head json data through custom api
- Variable `heads` = current heads being displayed
- Variable `totalHeads` = hold all the heads fetched

## API
- Added an api you can use instead of using [headdb.org](https://headdb.org/)
  - Returns a json document with:
  - Head name
  - Head UUID that [headdb.org](https://headdb.org/) uses
  - Head url for the minecraft texture
  - Head category, such as Blocks, Characters, etc.
  - Head `/give` command, 1.20+ commands
- It gets the categories by fetching through all the api's individually

## Aditional information
All the information is fetched from [headdb.org](https://headdb.org/). It only contains 900 heads, sadly, but for now it's the only option. In the meantime, @stephendotgg is currently contacting the people from https://minecraft-heads.com/ to see if we can use it's api, which has 50.000+ heads.

Please do let me know if I have to change anything!
Sorry in advance if this is a little scuffed, I made this in a hurry.

### CODE REVIEW

**Comment by joshbker** [comment]
@StillLutto what's the state of this? Is it something you believe is in a position to be reviewed and tested?

**Comment by StillLutto** [comment]
@joshbker Yes it most definitely is. Stephen was waiting to review it because he was contacting the minecraft-heads team for a better and more extensive api, I don't know how that ended though.

**Comment by stephendotgg** [comment]
@StillLutto We could not agree on terms in the end. 

For the record, I love your implementation here. Fits our theme nicely and looks like it could work well.

My only fear is that when sites like mc heads and the other ones have nearing 100,000 heads, I feel it a bit shameful to release with only 900+.

I absolutely want this contribution to be merged into the main project, but I want to work on getting more heads.

If you give me some time, I have a few tricks up my sleeve and will sort this issue.

**Comment by StillLutto** [comment]
@stephendotgg I completely agree, and if you can't get a deal, it's fine if it doesn't get implemented. Actually, I'd even prefer if you didn't implement this utility if you don't get a deal because it is quite scummy to do so with only 900+ heads. It's really sad that I only realized this when I was like halfway done making the util. [c58690b](https://github.com/flytegg/mc-utils/pull/211/commits/c58690ba614cf867bb1c33db86073b50c4947f82)

**Comment by StillLutto** [comment]
Btw, feel free to close this now.

**Pull request closed without merging**
